### ISSUE TITLE
Plans to adapt the exposure risk calculation to more infectious new variants

### ISSUE THREAD

**Issue by r-r-liu** [SwissCovid/swisscovid-doc#1]
Are there any plans to adapt the exposure risk calculation to the dominance of more infectious variants than the initial "wild" variant on which the current calculation is based.

My recommendations in comments to articles in the popular press to use SwissCovid and NotifyMe, resp. to use the enhanced SwissCovid ver. 2.0, have met with dismissive comments to the effect that 15 minutes is much too long, 10 seconds exposure to delta suffices for an infection, and things to that effect.  Of course, as Prof. Sandra Ciesek points out in NDRInfo's Coronavirus-Update, she's read such things as well, and they never clarify under what conditions 10 seconds suffices.

As I understand the exposure risk calculation, it's the sum of close contacts throughout the day that determines the risk, so it probably would make little sense to lower the critical time until delta becomes dominant.  I would appreciate any thoughts and insights in this regard, particularly from the app developers.

**Comment by simonroesch** [comment]
The SwissCovid app is following the official guidelines and guiding values of the classical contact tracing. The adaption of the currently used values (note: 1.5 meters and 15min accumulated contact time) is continuously reviewed. Should there be a change of the values in classical contact tracing, the thresholds of the SwissCovid app would be adapted accordingly.

**Comment by r-r-liu** [comment]
Yes, this is just as I suspected and expected. I raised the issue in response to some claims I read by "hobby -ologists" who justified not using the app with the claim that the Delta variant, in the meantime the dominant one in Switzerland, spreads much faster and hence requires less than fifteen minutes of close contact to infect.
