### ISSUE TITLE
Is NotifyMe functionality in SwissCovid compatible with German CoronaWarn app?

### ISSUE THREAD

**Issue by r-r-liu** [SwissCovid/swisscovid-doc#2]
From this [page](https://www.berliner-philharmoniker.de/en/concerts/visiting-information/) I surmise that CoronaWarn, the German counterpart to the original SwissCovid app, has, in a more recent version, gained check-in functionality, as has SwissCovid as of June 2021.  Are presence contacts also being exchanged between CoronaWarn and SwissCovid, or is the compatibility between the two limited to close contacts?

**Comment by simonroesch** [comment]
In the current implementation presence contacts are not exchanged with CoronaWarn, it is only possible to check in with the SwissCovid app at locations where SwissCovid-QR-Codes are provided.

**Comment by r-r-liu** [comment]
OK, thanks.  Too bad.
